author = Giuseppe Vittucci and Artur Tarassow
email = giuseppe.vittucci@gmail.com
version = 1.8
date = 2023-04-12
description = Moving Blocks Bootstrap (MBB) for linear panels
tags = C10
min-version = 2022b
public = pmbb
help = pmbb_help.txt
sample-script = pmbb_sample.inp