author = Giuseppe Vittucci and Artur Tarassow
email = giuseppe.vittucci@gmail.com
version = 2.0
date = 2023-05-11
description = Moving Blocks Bootstrap (MBB) for linear panels
tags = C10
min-version = 2022b
public = pmbb
help = pmbb_help.md
sample-script = pmbb_sample.inp
